before_script:
- git submodule init
- git submodule update

variables:
  PACKAGES_LINUX: >-
    flaw-al
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-audio
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-collada
    flaw-editor
    flaw-ffi
    flaw-ffmpeg
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-gl
    flaw-gl-mesa
    flaw-gl-sdl
    flaw-graphics
    flaw-input
    flaw-lua
    flaw-lua-refimpl
    flaw-math
    flaw-network
    flaw-oil
    flaw-oil-client
    flaw-oil-server
    flaw-physics
    flaw-sdl
    flaw-sl
    flaw-social
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-visual
    flaw-websocket-server
    flaw-window
  PACKAGES_WINDOWS: >-
    flaw-al
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-audio
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-collada
    flaw-dx11
    flaw-editor
    flaw-ffi
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-graphics
    flaw-input
    flaw-lua
    flaw-lua-refimpl
    flaw-math
    flaw-network
    flaw-oil
    flaw-oil-client
    flaw-oil-server
    flaw-physics
    flaw-sl
    flaw-social
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-visual
    flaw-websocket-server
    flaw-window
  PACKAGES_WEB: >-
    flaw-app
    flaw-asset
    flaw-audio
    flaw-base
    flaw-build
    flaw-canvas
    flaw-ffi
    flaw-game
    flaw-gl
    flaw-graphics
    flaw-input
    flaw-js
    flaw-math
    flaw-network
    flaw-physics
    flaw-sl
    flaw-social
    flaw-window
  INTEGERSIMPLE_CONFIG_FIX: >-
    powershell
    "Add-Content stack.yaml \"extra-deps: [cereal-text-0.1.0.1]\""
  INTEGERSIMPLE_FLAGS_WINDOWS: >-
    --ghc-variant integersimple
    --flag text:integer-simple
    --flag hashable:-integer-gmp
    --flag cryptonite:-integer-gmp
    --flag scientific:integer-simple
  FIX_TH_WINDOWS: >-
    powershell
    "Add-Content flaw-asset-dxt\flaw-asset-dxt.cabal \"  extra-ghci-libraries: all\";
    Add-Content flaw-font-fthb\flaw-font-fthb.cabal \"  extra-ghci-libraries: all\";
    Add-Content flaw-lua-refimpl\flaw-lua-refimpl.cabal \"  extra-ghci-libraries: all\""

linux:
  script:
  - "mkdir bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path bin $PACKAGES_LINUX"
  artifacts:
    name: "flaw-linux_x64-$CI_BUILD_ID"
    paths:
    - bin
  tags:
  - haskellstack
  - linux
  - x64

windows:
  script:
  - "%FIX_TH_WINDOWS%"
  - "%INTEGERSIMPLE_CONFIG_FIX%"
  - "mkdir bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path bin %INTEGERSIMPLE_FLAGS_WINDOWS% %PACKAGES_WINDOWS%"
  artifacts:
    name: "flaw-windows_x64-$CI_BUILD_ID"
    paths:
    - bin
  tags:
  - haskellstack
  - windows
  - x64

web:
  script:
  - "stack --no-terminal --compiler ghcjs-0.2.0_ghc-7.10.3 build --test $PACKAGES_WEB"
  tags:
  - haskellstack
  - ghcjs
  - linux
  - x64

linux-arm:
  script:
  - "mkdir bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path bin $PACKAGES_LINUX"
  artifacts:
    name: "flaw-linux_arm-$CI_BUILD_ID"
    paths:
    - bin
  tags:
  - haskellstack
  - linux
  - arm

pages:
  stage: deploy
  dependencies: []
  script:
  - "stack --no-terminal build --test --haddock --coverage $PACKAGES_LINUX"
  - "mkdir public"
  - "hlint . --cross --no-exit-code --quiet --report=public/hlint.html"
  - "mv $(stack path --local-doc-root) public/docs"
  - "mv $(stack path --local-hpc-root) public/hpc"
  - "curl -o public/docs/badge.svg https://img.shields.io/badge/haddock-$(date +%Y/%m/%d)-blue.svg"
  - "curl -o public/hpc/badge.svg https://img.shields.io/badge/test%20coverage-$(date +%Y/%m/%d)-orange.svg"
  tags:
  - haskellstack
  - linux
  - x64
  artifacts:
    paths:
    - public
  only:
  - master
