before_script:
- git submodule init
- git submodule update

variables:
  PACKAGES_LINUX: >-
    flaw-al
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-asset-wai
    flaw-audio
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-collada
    flaw-editor
    flaw-ffi
    flaw-ffmpeg
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-gl
    flaw-gl-mesa
    flaw-gl-sdl
    flaw-graphics
    flaw-input
    flaw-lmdb
    flaw-lua
    flaw-lua-refimpl
    flaw-math
    flaw-network
    flaw-oil
    flaw-oil-client
    flaw-oil-server
    flaw-physics
    flaw-sdl
    flaw-sl
    flaw-social
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-visual
    flaw-vulkan
    flaw-websocket-server
    flaw-window
  PACKAGES_WINDOWS: >-
    flaw-al
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-audio
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-collada
    flaw-dx11
    flaw-editor
    flaw-ffi
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-gl
    flaw-gl-win32
    flaw-graphics
    flaw-input
    flaw-lmdb
    flaw-lua
    flaw-lua-refimpl
    flaw-math
    flaw-network
    flaw-oil
    flaw-oil-client
    flaw-physics
    flaw-sl
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-visual
    flaw-vulkan
    flaw-window
  PACKAGES_MACOS: >-
    flaw-al
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-audio
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-collada
    flaw-editor
    flaw-ffi
    flaw-ffmpeg
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-gl
    flaw-gl-sdl
    flaw-graphics
    flaw-input
    flaw-lmdb
    flaw-lua
    flaw-lua-refimpl
    flaw-math
    flaw-network
    flaw-oil
    flaw-oil-client
    flaw-physics
    flaw-sdl
    flaw-sl
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-visual
    flaw-window
  PACKAGES_WEB: >-
    flaw-app
    flaw-asset
    flaw-audio
    flaw-base
    flaw-build
    flaw-canvas
    flaw-ffi
    flaw-game
    flaw-gl
    flaw-graphics
    flaw-input
    flaw-js
    flaw-math
    flaw-network
    flaw-physics
    flaw-sl
    flaw-social
    flaw-websocket-client
    flaw-window

linux:
  script:
  - "mkdir -p flaw-linux/bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path flaw-linux/bin $PACKAGES_LINUX"
  - "stack --no-terminal build --test --flag flaw-app:vulkan flaw-app"
  artifacts:
    name: "flaw-linux_x64-$CI_BUILD_ID"
    paths:
    - flaw-linux
    expire_in: 1 week
  tags:
  - haskellstack
  - linux
  - x64
  except:
  - arm
  - pages

windows:
  script:
  - "mkdir flaw-windows\\bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path flaw-windows/bin %PACKAGES_WINDOWS%"
  - "stack --no-terminal build --test --flag flaw-app:vulkan flaw-app"
  - "stack --no-terminal build --test --flag flaw-app:-dx11 flaw-app"
  - "stack --no-terminal build --test --flag flaw-app:-gl flaw-app"
  artifacts:
    name: "flaw-windows_x64-$CI_BUILD_ID"
    paths:
    - flaw-windows
    expire_in: 1 week
  tags:
  - haskellstack
  - windows
  - x64
  except:
  - arm
  - pages

macos:
  script:
  - "mkdir -p flaw-macos/bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path flaw-macos/bin $PACKAGES_MACOS"
  artifacts:
    name: "flaw-macos_x64-$CI_BUILD_ID"
    paths:
    - flaw-macos
    expire_in: 1 week
  tags:
  - haskellstack
  - macos
  - x64
  except:
  - arm
  - pages

web:
  script:
  - "stack --no-terminal --compiler ghcjs-0.2.0_ghc-8.0.1 build --test $PACKAGES_WEB"
  tags:
  - haskellstack
  - ghcjs
  - linux
  - x64
  except:
  - arm
  - pages

linux-arm:
  script:
  - "mkdir -p flaw-linux-arm/bin"
  - "stack --no-terminal build --test --copy-bins --local-bin-path flaw-linux-arm/bin $PACKAGES_LINUX"
  artifacts:
    name: "flaw-linux_arm-$CI_BUILD_ID"
    paths:
    - flaw-linux-arm
    expire_in: 1 week
  tags:
  - haskellstack
  - linux
  - arm
  only:
  - arm
  except:
  - pages

itch:
  stage: deploy
  environment: itch
  dependencies:
  - linux
  - windows
  - macos
  script:
  - "mkdir linux && mv flaw-linux/bin/model-editor linux/"
  - "mkdir windows && mv flaw-windows/bin/model-editor.exe windows/"
  - "mkdir macos && mv flaw-macos/bin/model-editor macos/"
  - "butler push linux quyse/flaw:model-editor-linux"
  - "butler push windows quyse/flaw:model-editor-windows"
  - "butler push macos quyse/flaw:model-editor-macos"
  tags:
  - linux
  - butler
  only:
  - master

pages:
  stage: deploy
  environment: pages
  dependencies: []
  script:
  - "stack --no-terminal build --test --haddock --coverage $PACKAGES_LINUX"
  - "mkdir public"
  - "hlint . --cross --no-exit-code --quiet --report=public/hlint.html"
  - "mv $(stack path --local-doc-root) public/docs"
  - "mv $(stack path --local-hpc-root) public/hpc"
  - "./pages/sanitize.sh public"
  - "tail -n +6 README.md | pandoc -f markdown_github -o public/index.html --template pages/index.html"
  tags:
  - haskellstack
  - linux
  - x64
  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  - pages
