before_script:
- git submodule init
- git submodule update

variables:
  PACKAGES_LINUX: >-
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-ffi
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-gl
    flaw-glsl
    flaw-graphics
    flaw-input
    flaw-math
    flaw-oil
    flaw-oil-client
    flaw-oil-server
    flaw-physics
    flaw-sdl
    flaw-sl
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-window
  PACKAGES_WINDOWS: >-
    flaw-app
    flaw-asset
    flaw-asset-dxt
    flaw-base
    flaw-build
    flaw-bullet
    flaw-canvas
    flaw-dx11
    flaw-ffi
    flaw-font
    flaw-font-fthb
    flaw-game
    flaw-graphics
    flaw-input
    flaw-math
    flaw-oil
    flaw-oil-client
    flaw-oil-server
    flaw-physics
    flaw-sl
    flaw-sqlite
    flaw-ui
    flaw-ui-default-style
    flaw-window
  PACKAGES_WEB: >-
    flaw-app
    flaw-asset
    flaw-base
    flaw-build
    flaw-canvas
    flaw-ffi
    flaw-glsl
    flaw-graphics
    flaw-input
    flaw-math
    flaw-physics
    flaw-sl
    flaw-webgl
    flaw-window
  INTEGERSIMPLE_FLAGS_WINDOWS: >-
    --ghc-variant integersimple
    --flag text:integer-simple
    --flag hashable:-integer-gmp
    --flag cryptonite:-integer-gmp
    --flag scientific:integer-simple
  FIX_TH_WINDOWS: "powershell \"Add-Content flaw-font-fthb\\flaw-font-fthb.cabal \\\"  extra-ghci-libraries: all\\\"\""

linux:
  script:
  - "stack --no-terminal test $PACKAGES_LINUX"
  tags:
  - haskellstack
  - linux

windows_gmp:
  script:
  - "%FIX_TH_WINDOWS%"
  - "stack --no-terminal test %PACKAGES_WINDOWS%"
  tags:
  - haskellstack
  - windows

windows_integersimple:
  script:
  - "%FIX_TH_WINDOWS%"
  - "stack --no-terminal test %INTEGERSIMPLE_FLAGS_WINDOWS% %PACKAGES_WINDOWS%"
  tags:
  - haskellstack
  - windows

web:
  script:
  - "stack --no-terminal --compiler ghcjs-0.2.0.20151029_ghc-7.10.2 test $PACKAGES_WEB"
  tags:
  - haskellstack
  - ghcjs
