# use new container infrastructure to enable caching
sudo: false

# choose a lightweight base image
language: c

# GMP needed for GHC
addons:
  apt:
    packages:
    - libgmp-dev

env:
# linux ghc build
- ARGS="                                           test flaw-app flaw-asset flaw-base flaw-build flaw-ffi flaw-font flaw-game flaw-gl flaw-glsl flaw-graphics flaw-input flaw-math flaw-physics flaw-sdl flaw-sl            flaw-window"
# web ghcjs build
- ARGS="--compiler ghcjs-0.1.0.20150924_ghc-7.10.2 test flaw-app flaw-asset flaw-base flaw-build flaw-ffi           flaw-game         flaw-glsl flaw-graphics flaw-input flaw-math flaw-physics          flaw-sl flaw-webgl flaw-window"

before_install:
# download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# download and install deps
- bash .travis-install.sh
- export PKG_CONFIG_PATH=$HOME/.deps/lib/pkgconfig
- export LD_LIBRARY_PATH=$HOME/.deps/lib

script: stack --no-terminal --install-ghc $ARGS

cache:
  directories:
  - $HOME/.stack
  - $HOME/.deps
