# use new container infrastructure to enable caching
sudo: false

# choose a lightweight base image
language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
- OPTS=
- OPTS="--ghc-options -fllvm"

before_install:
# download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# download and install deps
- bash .travis-install.sh
- export PKG_CONFIG_PATH=$HOME/.deps/lib/pkgconfig
- export LD_LIBRARY_PATH=$HOME/.deps/lib

script: stack --no-terminal --install-ghc test $OPTS flaw-app flaw-asset flaw-base flaw-build flaw-canvas flaw-ffi flaw-font flaw-game flaw-gl flaw-glsl flaw-graphics flaw-input flaw-math flaw-oil flaw-oil-client flaw-oil-server flaw-physics flaw-sdl flaw-sl flaw-sqlite flaw-ui flaw-ui-default-style flaw-window

cache:
  directories:
  - $HOME/.stack
  - $HOME/.deps
