# use new container infrastructure to enable caching
sudo: false

# choose a lightweight base image
language: c

matrix:
  include:
  - os: linux
    env: OS=linux GHCVER=7.10.3
    addons:
      apt:
        packages:
        - ghc-7.10.3
        - libopenal-dev
        sources:
        - hvr-ghc
  - os: linux
    env: OS=linux GHCVER=HEAD
    addons:
      apt:
        packages:
        - ghc-head
        - libopenal-dev
        sources:
        - hvr-ghc
  - os: osx
    env: OS=osx
  allow_failures:
  - env: OS=linux GHCVER=HEAD

before_install:
- |-
  case "$OS" in
  linux)
    mkdir -p ~/.local/bin && \
    export PATH=$HOME/.local/bin:$PATH && \
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' && \
    bash .travis-install.sh && \
    export PKG_CONFIG_PATH=$HOME/.deps/lib/pkgconfig && \
    export LD_LIBRARY_PATH=$HOME/.deps/lib
    ;;
  osx)
    brew update && \
    brew install haskell-stack openal-soft sdl2
    ;;
  esac

script: >-
  stack --no-terminal --install-ghc test
  flaw-al
  flaw-app
  flaw-asset
  flaw-asset-dxt
  flaw-audio
  flaw-base
  flaw-build
  flaw-bullet
  flaw-canvas
  flaw-collada
  flaw-editor
  flaw-ffi
  flaw-font
  flaw-font-fthb
  flaw-game
  flaw-gl
  flaw-graphics
  flaw-input
  flaw-lua
  flaw-lua-refimpl
  flaw-math
  flaw-oil
  flaw-oil-client
  flaw-oil-server
  flaw-physics
  flaw-sdl
  flaw-sl
  flaw-sqlite
  flaw-ui
  flaw-ui-default-style
  flaw-visual
  flaw-window

cache:
  directories:
  - $HOME/.stack
  - $HOME/.deps
