environment:
  global:
    STACK_ROOT: "c:\\sr"

clone_folder: "c:\\ws"

install:
- curl -ostack.zip -L https://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

test_script:
- stack --no-terminal test flaw-app flaw-asset flaw-base flaw-build flaw-canvas flaw-dx11 flaw-ffi flaw-font flaw-game flaw-graphics flaw-input flaw-math flaw-oil flaw-oil-client flaw-oil-editor flaw-oil-server flaw-physics flaw-sl flaw-sqlite flaw-ui flaw-ui-default-style flaw-window
