environment:
  GRUMPY_ARTIFACT_REPO_URL: github.com/grumpy-bot/flaw-build-cache
  GRUMPY_ARTIFACT_REPO_PATH: c:\\grc
  GRUMPY_ARTIFACT_REPO_USERNAME: grumpy-bot
  GRUMPY_ARTIFACT_REPO_PASSWORD:
    secure: 8dwmnvRlS9CYmjvuBJaDa+m4VpVEU+oZkEty/RgieclyhhQUgDbL2/26tWHXNry1
  STACK_ROOT: "c:\\sr"

clone_folder: "c:\\ws"

install:
- git submodule init
- git submodule update
- git clone https://gist.github.com/7178ec5737235bdf60bf.git grumpy-cache && grumpy-cache\stack-appveyor-cache.bat init

build: off

test_script:
- stack setup > nul
# hack for "0: Bad file descriptor" error
- echo "" | stack --no-terminal test flaw-app flaw-asset flaw-base flaw-build flaw-canvas flaw-dx11

on_finish:
- grumpy-cache\stack-appveyor-cache.bat finish
