resolver: integer-simple-snapshot.yaml

packages:
- flaw-al
- flaw-app
- flaw-asset
- flaw-asset-dxt
- flaw-asset-wai
- flaw-audio
- flaw-base
- flaw-build
- flaw-bullet
- flaw-canvas
- flaw-collada
- flaw-dx11
- flaw-editor
- flaw-ffi
- flaw-ffmpeg
- flaw-font
- flaw-font-fhi
- flaw-font-icu
- flaw-game
- flaw-gamejolt-webapi
- flaw-gl
- flaw-gl-mesa
- flaw-gl-sdl
- flaw-gl-win32
- flaw-graphics
- flaw-input
- flaw-itch-webapi
- flaw-js
- flaw-lmdb
- flaw-lua
- flaw-lua-refimpl
- flaw-math
- flaw-math-determ
- flaw-network
- flaw-oil
- flaw-oil-client
- flaw-oil-server
- flaw-physics
- flaw-script
- flaw-sdl
- flaw-sl
- flaw-social
- flaw-sqlite
- flaw-steam
- flaw-steam-encryptedticket
- flaw-steam-webapi
- flaw-ui
- flaw-ui-default-style
- flaw-ui-default-style-data
- flaw-visual
- flaw-vulkan
- flaw-websocket-client
- flaw-websocket-server
- flaw-window

extra-deps:
- uuid-1.3.13

allow-newer: true

ghc-options:
  "$locals": -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -Wno-tabs
