resolver: lts-5.9

packages:
- flaw-al
- flaw-app
- flaw-asset
- flaw-asset-dxt
- flaw-audio
- flaw-base
- flaw-build
- flaw-bullet
- flaw-canvas
- flaw-collada
- flaw-dx11
- flaw-editor
- flaw-ffi
- flaw-ffmpeg
- flaw-font
- flaw-font-fthb
- flaw-game
- flaw-gl
- flaw-gl-sdl
- flaw-graphics
- flaw-input
- flaw-js
- flaw-lua
- flaw-lua-refimpl
- flaw-math
- flaw-oil
- flaw-oil-client
- flaw-oil-server
- flaw-physics
- flaw-sdl
- flaw-sl
- flaw-sqlite
- flaw-ui
- flaw-ui-default-style
- flaw-visual
- flaw-window

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
