resolver: lts-6.0

packages:
- flaw-al
- flaw-app
- flaw-asset
- flaw-asset-dxt
- flaw-asset-wai
- flaw-audio
- flaw-base
- flaw-build
- flaw-bullet
- flaw-canvas
- flaw-collada
- flaw-dx11
- flaw-editor
- flaw-ffi
- flaw-ffmpeg
- flaw-font
- flaw-font-fthb
- flaw-game
- flaw-gl
- flaw-gl-mesa
- flaw-gl-sdl
- flaw-graphics
- flaw-input
- flaw-js
- flaw-lua
- flaw-lua-refimpl
- flaw-math
- flaw-network
- flaw-oil
- flaw-oil-client
- flaw-oil-entity
- flaw-oil-server
- flaw-physics
- flaw-sdl
- flaw-sl
- flaw-social
- flaw-sqlite
- flaw-ui
- flaw-ui-default-style
- flaw-visual
- flaw-websocket-client
- flaw-websocket-server
- flaw-window
# sdl2 fork without heavy dependencies
- location:
    git: https://github.com/quyse/sdl2.git
    commit: 3faecd7f63f8a18300d4caaf3735d7b3a5039d1b
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
