resolver: lts-5.5

packages:
- flaw-app
- flaw-asset
- flaw-asset-dxt
- flaw-base
- flaw-build
- flaw-bullet
- flaw-canvas
- flaw-collada
- flaw-dx11
- flaw-ffi
- flaw-font
- flaw-font-fthb
- flaw-game
- flaw-gl
- flaw-glsl
- flaw-graphics
- flaw-input
- flaw-lua
- flaw-lua-refimpl
- flaw-math
- flaw-oil
- flaw-oil-client
- flaw-oil-server
- flaw-physics
- flaw-sdl
- flaw-sl
- flaw-sqlite
- flaw-ui
- flaw-ui-default-style
- flaw-visual
- flaw-window
- location:
    git: https://github.com/ghcjs/ghcjs-dom
    commit: b94aa57a9cd64d04689fdce32f68da35b75c1d28
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
