resolver: nightly-2016-06-12

packages:
- flaw-al
- flaw-app
- flaw-asset
- flaw-asset-dxt
- flaw-asset-wai
- flaw-audio
- flaw-base
- flaw-build
- flaw-bullet
- flaw-canvas
- flaw-collada
- flaw-dx11
- flaw-editor
- flaw-ffi
- flaw-ffmpeg
- flaw-font
- flaw-font-fthb
- flaw-game
- flaw-gl
- flaw-gl-mesa
- flaw-gl-sdl
- flaw-graphics
- flaw-input
- flaw-js
- flaw-lua
- flaw-lua-refimpl
- flaw-math
- flaw-network
- flaw-oil
- flaw-oil-client
- flaw-oil-entity
- flaw-oil-server
- flaw-physics
- flaw-sdl
- flaw-sl
- flaw-social
- flaw-sqlite
- flaw-ui
- flaw-ui-default-style
- flaw-visual
- flaw-vulkan
- flaw-websocket-client
- flaw-websocket-server
- flaw-window
# sdl2 fork without heavy dependencies
- location:
    git: https://github.com/quyse/sdl2.git
    commit: cc66bf8d7bd1ca5bb01712d7a890dee647e1f351
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2

ghc-options:
  "*": -O3 -threaded -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
