cabal-version:       3.0
name:                flaw-asset-dxt
version:             0.1.0.0
-- synopsis:            
-- description:         
license:             MIT
license-file:        LICENSE
author:              Alexander Bich
maintainer:          quyse0@gmail.com
-- copyright:           
category:            Game
build-type:          Simple
-- extra-source-files:  

source-repository head
  type: git
  location: https://github.com/quyse/flaw.git
  subdir: flaw-asset-dxt

library
  exposed-modules:
    Flaw.Asset.Texture.Dxt
  build-depends:
    base
    , bytestring
    , flaw-base
    , flaw-graphics
    , memory
  ghc-options:         -Wall
  default-language:    Haskell2010
  cxx-sources:
    -- libsquish
    src/alpha.cpp
    src/clusterfit.cpp
    src/colourblock.cpp
    src/colourfit.cpp
    src/colourset.cpp
    src/maths.cpp
    src/rangefit.cpp
    src/singlecolourfit.cpp
    src/squish.cpp
    -- helpers
    src/flaw-squish.cpp
  cxx-options: -O3 -fno-exceptions -fno-rtti
  if arch(x86_64)
    cxx-options: -DSQUISH_USE_SSE=2
