cabal-version:       3.0
name:                flaw-font-fhi
version:             0.1.0.0
-- synopsis:            
-- description:         
license:             MIT
license-file:        LICENSE
author:              Alexander Bich
maintainer:          quyse0@gmail.com
-- copyright:           
category:            Game
build-type:          Simple
-- extra-source-files:  

source-repository head
  type: git
  location: https://github.com/quyse/flaw.git
  subdir: flaw-font-fhi

flag icu
  description:       build with icu
  default:           False
  manual:            True

library
  exposed-modules:
    Flaw.Graphics.Font.FreeType
    Flaw.Graphics.Font.Harfbuzz
  other-modules:
    Flaw.Graphics.Font.FreeType.FFI
  build-depends:
    base
    , bytestring
    , flaw-ffi
    , flaw-font
    , flaw-math
    , JuicyPixels
    , mtl
    , stm
    , text
    , unordered-containers
    , vector
  if flag(icu)
    build-depends:       flaw-font-icu
  ghc-options:         -Wall
  default-language:    Haskell2010
  c-sources:
    -- Helpers
    src/flaw-ft.c
  extra-libraries: freetype, harfbuzz
