{-|
Module: Flaw.Graphics.Vulkan.FFI
Description: Vulkan FFI.
License: MIT
-}

{-# LANGUAGE CPP, PatternSynonyms, TemplateHaskell #-}

module Flaw.Graphics.Vulkan.FFI
	(
	-- * version
	  pattern VK_API_VERSION
	-- * general
	, VkResult(..)
	, VkStructureType(..)
	, VkFlags
	-- * allocation
	, VkSystemAllocationScope(..)
	, VkInternalAllocationType(..)
	, FN_vkAllocationFunction
	, FN_vkReallocationFunction
	, FN_vkFreeFunction
	, FN_vkInternalAllocationNotification
	, FN_vkInternalFreeNotification
	, VkAllocationCallbacks(..)
	-- * instances
	, VkInstance
	, VkApplicationInfo(..)
	, VkInstanceCreateFlags
	, VkInstanceCreateInfo(..)
	, vkCreateInstance
	) where

import Data.Word
import Foreign.C.Types
import Foreign.Ptr

import Flaw.FFI
import Flaw.Graphics.Vulkan.FFI.TH

-- Vulkan API convention for foreign definitions
#if defined(mingw32_HOST_OS)
#define VKAPI_CALL stdcall
#else
#define VKAPI_CALL ccall
#endif


-- version
pattern VK_API_VERSION :: Word32
pattern VK_API_VERSION = 400017


-- general

-- | VkResult
genEnum [t|Word32|] "VkResult"
	[ ("VK_SUCCESS", 0)
	, ("VK_NOT_READY", 1)
	, ("VK_TIMEOUT", 2)
	, ("VK_EVENT_SET", 3)
	, ("VK_EVENT_RESET", 4)
	, ("VK_INCOMPLETE", 5)
	, ("VK_ERROR_OUT_OF_HOST_MEMORY", -1)
	, ("VK_ERROR_OUT_OF_DEVICE_MEMORY", -2)
	, ("VK_ERROR_INITIALIZATION_FAILED", -3)
	, ("VK_ERROR_DEVICE_LOST", -4)
	, ("VK_ERROR_MEMORY_MAP_FAILED", -5)
	, ("VK_ERROR_LAYER_NOT_PRESENT", -6)
	, ("VK_ERROR_EXTENSION_NOT_PRESENT", -7)
	, ("VK_ERROR_FEATURE_NOT_PRESENT", -8)
	, ("VK_ERROR_INCOMPATIBLE_DRIVER", -9)
	, ("VK_ERROR_TOO_MANY_OBJECTS", -10)
	, ("VK_ERROR_FORMAT_NOT_SUPPORTED", -11)
	, ("VK_ERROR_FRAGMENTED_POOL", -12)
	, ("VK_ERROR_SURFACE_LOST_KHR", -1000000000)
	, ("VK_ERROR_NATIVE_WINDOW_IN_USE_KHR", -1000000001)
	, ("VK_SUBOPTIMAL_KHR", 1000001003)
	, ("VK_ERROR_OUT_OF_DATE_KHR", -1000001004)
	, ("VK_ERROR_INCOMPATIBLE_DISPLAY_KHR", -1000003001)
	, ("VK_ERROR_VALIDATION_FAILED_EXT", -1000011001)
	, ("VK_ERROR_INVALID_SHADER_NV", -1000012000)
	]


-- structures

-- | VkStructureType
genEnum [t|Word32|] "VkStructureType"
	[ ("VK_STRUCTURE_TYPE_APPLICATION_INFO", 0)
	, ("VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO", 1)
	, ("VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO", 2)
	, ("VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO", 3)
	, ("VK_STRUCTURE_TYPE_SUBMIT_INFO", 4)
	, ("VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO", 5)
	, ("VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE", 6)
	, ("VK_STRUCTURE_TYPE_BIND_SPARSE_INFO", 7)
	, ("VK_STRUCTURE_TYPE_FENCE_CREATE_INFO", 8)
	, ("VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO", 9)
	, ("VK_STRUCTURE_TYPE_EVENT_CREATE_INFO", 10)
	, ("VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO", 11)
	, ("VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO", 12)
	, ("VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO", 13)
	, ("VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO", 14)
	, ("VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO", 15)
	, ("VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO", 16)
	, ("VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO", 17)
	, ("VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO", 18)
	, ("VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO", 19)
	, ("VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO", 20)
	, ("VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO", 21)
	, ("VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO", 22)
	, ("VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO", 23)
	, ("VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO", 24)
	, ("VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO", 25)
	, ("VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO", 26)
	, ("VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO", 27)
	, ("VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO", 28)
	, ("VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO", 29)
	, ("VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO", 30)
	, ("VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO", 31)
	, ("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO", 32)
	, ("VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO", 33)
	, ("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO", 34)
	, ("VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET", 35)
	, ("VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET", 36)
	, ("VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO", 37)
	, ("VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO", 38)
	, ("VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO", 39)
	, ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO", 40)
	, ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO", 41)
	, ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO", 42)
	, ("VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO", 43)
	, ("VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER", 44)
	, ("VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER", 45)
	, ("VK_STRUCTURE_TYPE_MEMORY_BARRIER", 46)
	, ("VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO", 47)
	, ("VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO", 48)
	, ("VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR", 1000001000)
	, ("VK_STRUCTURE_TYPE_PRESENT_INFO_KHR", 1000001001)
	, ("VK_STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR", 1000002000)
	, ("VK_STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR", 1000002001)
	, ("VK_STRUCTURE_TYPE_DISPLAY_PRESENT_INFO_KHR", 1000003000)
	, ("VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR", 1000004000)
	, ("VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR", 1000005000)
	, ("VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR", 1000006000)
	, ("VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR", 1000007000)
	, ("VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR", 1000008000)
	, ("VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR", 1000009000)
	, ("VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT", 1000011000)
	, ("VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD", 1000018000)
	, ("VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT", 1000022000)
	, ("VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_TAG_INFO_EXT", 1000022001)
	, ("VK_STRUCTURE_TYPE_DEBUG_MARKER_MARKER_INFO_EXT", 1000022002)
	, ("VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV", 1000026000)
	, ("VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV", 1000026001)
	, ("VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV", 1000026002)
	]

type VkFlags = Word32

-- allocation

genEnum [t|Word32|] "VkSystemAllocationScope"
	[ ("VK_SYSTEM_ALLOCATION_SCOPE_COMMAND", 0)
	, ("VK_SYSTEM_ALLOCATION_SCOPE_OBJECT", 1)
	, ("VK_SYSTEM_ALLOCATION_SCOPE_CACHE", 2)
	, ("VK_SYSTEM_ALLOCATION_SCOPE_DEVICE", 3)
	, ("VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE", 4)
	]

genEnum [t|Word32|] "VkInternalAllocationType"
	[ ("VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE", 0)
	]

type FN_vkAllocationFunction =  Ptr () -> CSize -> CSize -> VkSystemAllocationScope -> IO (Ptr ())
type FN_vkReallocationFunction = Ptr () -> Ptr () -> CSize -> CSize -> VkSystemAllocationScope -> IO (Ptr ())
type FN_vkFreeFunction = Ptr () -> Ptr () -> IO ()
type FN_vkInternalAllocationNotification = Ptr () -> CSize -> VkInternalAllocationType -> VkSystemAllocationScope -> IO ()
type FN_vkInternalFreeNotification = Ptr () -> CSize -> VkInternalAllocationType -> VkSystemAllocationScope -> IO ()

genStruct "VkAllocationCallbacks"
	[ ([t|Ptr ()|], "pUserData")
	, ([t|FunPtr FN_vkAllocationFunction|], "pfnAllocation")
	, ([t|FunPtr FN_vkReallocationFunction|], "pfnReallocation")
	, ([t|FunPtr FN_vkFreeFunction|], "pfnFree")
	, ([t|FunPtr FN_vkInternalAllocationNotification|], "pfnInternalAllocation")
	, ([t|FunPtr FN_vkInternalFreeNotification|], "pfnInternalFree")
	]

-- instances

vkDefineHandle "VkInstance"

genStruct "VkApplicationInfo"
	[ ([t|VkStructureType|], "sType")
	, ([t|Ptr ()|], "pNext")
	, ([t|Ptr CChar|], "pApplicationName")
	, ([t|Word32|], "applicationVersion")
	, ([t|Ptr CChar|], "pEngineName")
	, ([t|Word32|], "engineVersion")
	, ([t|Word32|], "apiVersion")
	]

type VkInstanceCreateFlags = VkFlags

genStruct "VkInstanceCreateInfo"
	[ ([t|VkStructureType|], "sType")
	, ([t|Ptr ()|], "pNext")
	, ([t|VkInstanceCreateFlags|], "flags")
	, ([t|Ptr VkApplicationInfo|], "pApplicationInfo")
	, ([t|Word32|], "enabledLayerCount")
	, ([t|Ptr (Ptr CChar)|], "ppEnabledLayerNames")
	, ([t|Word32|], "enabledExtensionCount")
	, ([t|Ptr (Ptr CChar)|], "ppEnabledExtensionNames")
	]

foreign import VKAPI_CALL safe vkCreateInstance
	:: Ptr VkInstanceCreateInfo
	-> Ptr VkAllocationCallbacks
	-> Ptr VkInstance
	-> IO Word32 -- VkResult
